# Use cached brew shellenv instead of running it every time (saves ~50ms)
# Cache is generated by: /opt/homebrew/bin/brew shellenv > ~/.cache/brew-shellenv.zsh
if [[ -f ~/.cache/brew-shellenv.zsh ]]; then
  source ~/.cache/brew-shellenv.zsh
else
  # Fallback if cache doesn't exist
  BREW_CMD=/opt/homebrew/bin/brew
  if [[ -e $BREW_CMD ]]; then
    eval "$(${BREW_CMD} shellenv)"
  fi
fi
