# Load cached pyenv init instead of running eval every time
# Cache is generated by: pyenv init - > ~/.cache/pyenv.zsh
# This saves ~50-100ms on shell startup
#
# To regenerate cache after updating pyenv:
#   pyenv init - > ~/.cache/pyenv.zsh

if [[ -f ~/.cache/pyenv.zsh ]]; then
  source ~/.cache/pyenv.zsh
fi
