# Load cached rbenv init instead of running eval every time
# Cache is generated by: rbenv init - | grep -v "rbenv rehash" > ~/.cache/rbenv.zsh
# This saves ~150-200ms on shell startup
#
# To regenerate cache after updating rbenv:
#   rbenv init - | grep -v "rbenv rehash" > ~/.cache/rbenv.zsh

if [[ -f ~/.cache/rbenv.zsh ]]; then
  source ~/.cache/rbenv.zsh
fi
